name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  L1_NETWORK_NAME: testnet
  MOVEVM_VERSION: v0.2.12

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile.linux.amd64
          load: true
          tags: initia:linux-amd64
      - name: Export binary
        run: |
          docker create --name temp initia:linux-amd64
          docker cp temp:/app ./app
          tar -czvf initia_${{ github.sha }}_Linux_amd64.tar.gz -C app .
          docker rm temp
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Upload to GCS
        run: gsutil cp initia_${{ github.sha }}_Linux_amd64.tar.gz gs://your-bucket-name/networks/${{ env.L1_NETWORK_NAME }}/binaries/
