name: Build and Upload to GCS

on:
  # push:
    # tags:
    #   - 'v*'
  push:
    branches:
      - "main"
      
jobs:
  # build-linux-amd64:
  #   uses: ./.github/workflows/build-linux-amd64.yml
  #   secrets: inherit

  build-linux-arm64:
    uses: ./.github/workflows/build-linux-arm64.yml
    secrets: inherit
