name: Multi-Architecture Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build for Linux-${{ matrix.arch }}
      env:
        ARCH: ${{ matrix.arch }}
        L1_VERSION: ${{ github.sha }}
        L1_NETWORK_NAME: testnet
        MOVEVM_VERSION: v0.2.12  # 적절한 버전으로 변경하세요
      run: |
        docker buildx build --platform linux/${{ matrix.arch }} \
          --file Dockerfile \
          --build-arg ARCH=${{ matrix.arch }} \
          --build-arg L1_VERSION=${{ env.L1_VERSION }} \
          --build-arg L1_NETWORK_NAME=${{ env.L1_NETWORK_NAME }} \
          --build-arg MOVEVM_VERSION=${{ env.MOVEVM_VERSION }} \
          --output type=local,dest=./output \
          .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: initia-linux-${{ matrix.arch }}
        path: ./output/initia_${{ env.L1_VERSION }}_Linux_${{ matrix.arch }}.tar.gz
